sudo: required
services:
  - docker

before_install:
  - docker build -t sbhasale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sbhasale/react-test npm test -- --coverage

after_success:
  - docker build -t sbhasale/multi-client  ./client
  - docker build -t sbhasale/multi-nginx ./nginx
  - docker build -t sbhasale/multi-server ./server
  - docker build -t sbhasale/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push sbhasale/multi-client
  - docker push sbhasale/multi-nginx
  - docker push sbhasale/multi-server
  - docker push sbhasale/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-067331374402'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

